name: test
description: test
runs:
  using: "composite"
  steps:
    - run: echo "::group::npx playwright install --with-deps"
      shell: bash
    - run: echo test123
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
    
