name: CI
on: [push]
jobs:
  with-miniconda:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: mxschmitt/setup-miniconda@master
      with:
        auto-update-conda: true
        python-version: "3.9"
    - run: |
        cat <<EOT >> example.bash
          false
          exit 0
        EOT
        bash example.bash
  without-miniconda:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        cat <<EOT >> example.bash
          false
          exit 0
        EOT
        bash example.bash
