name: CI
on: [push]
jobs:
  with-miniconda:
    runs-on: ubuntu-latest
    name: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate sessionf
      uses: mxschmitt/action-tmate@bugfix/limit-access-to-actor
      with:
        limit-access-to-actor: true
