name: CI
on: [push]
jobs:
  test_e2e:
    runs-on: ubuntu-20.04
    container:
      image: mcr.microsoft.com/playwright:v1.10.0-focal
      options: '--ipc=host --entrypoint /bin/bash --user root'
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: node script.js