name: "tests repro"

on:
  push:
    branches:
      - main

jobs:
  test_upload:
    name: upload
    runs-on: macos-14-large
    steps:
    - uses: actions/checkout@v4
    - name: Prepare environment
      run: arch
