name: CI
on: [push]
jobs:
  build-mac:
    runs-on: macos-14-large
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - run: node --version
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: node --version
