name: tests
on: [push, pull_request]
jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 14, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@master
