name: "test1"

on:
  push:
    branches:
      - main

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    environment: Test
    strategy:
      matrix:
        runs-on: [macos-12, macos-13, macos-14]
    steps:
    - uses: actions/checkout@v4
    - run: |
        sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR IGNORE INTO access VALUES ('kTCCServiceMicrophone','/usr/local/opt/runner/provisioner/provisioner',1,2,4,1,NULL,NULL,0,'UNUSED',NULL,0,1687786159,NULL,NULL,'UNUSED',1687786159);"
      shell: bash