name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-2025
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
