name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        docker run \
          --rm \
          --name docker-tests \
          --platform linux/arm64 \
          -t \
          ubuntu:noble /bin/bash -c '
            set -e
            apt-get update && apt-get install -y curl

            curl -O https://playwright.azureedge.net/builds/driver/next/playwright-1.47.0-beta-1726138322000-mac.zip
          '
