name: "test1"

on:
  push:
    branches:
      - main

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/download-artifact/
