name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        git clone https://github.com/microsoft/playwright
        cd playwright
        npm i && npm run build
        DEBUG=pw:install npx playwright install --with-deps chromium
        /home/runner/.cache/ms-playwright/chromium-1153/chrome-linux/chrome --headless --timeout=5000 --screenshot=screenshot.png https://example.com
