name: Test Conditions

on: [push]

jobs:
  test-conditions:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Always runs
        run: echo "This is step 1"

      - name: Step 2 - Set output
        id: set-output
        run: |
          echo "status=123" >> "$GITHUB_OUTPUT"
          exit 1

      - name: Step 3 - Check output
        if: steps.set-output.outputs.status == '123'
        run: echo "Output status is 123"
