name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
