name: "tests repro"

on:
  push:
    branches:
      - main

jobs:
  amd:
    name: upload2
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - run: arch

  arm:
    name: upload
    runs-on: macos-14-xlarge
    steps:
    - uses: actions/checkout@v4
    - run: arch
