name: "tests repro"

on:
  push:
    branches:
      - main

jobs:
  arm:
    name: upload
    runs-on: macos-14-xlarge
    steps:
    - uses: ./.github/actions/download-artifact/action.yml
    - uses: actions/checkout@v4
    - run: arch
