name: "test2"

on:
  push:
    branches:
      - main

jobs:
  test2:
    name: test2
    strategy:
      matrix:
        runs-on: [windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - run: uname
      shell: bash
