name: Take Screenshot with Chrome Beta

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  screenshot:
    name: Take Screenshot
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13-large, macos-13-xlarge]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Take screenshot with Chrome Beta
      run: node -e "console.log(os.arch())"

