name: "test1"

on:
  push:
    branches:
      - main

jobs:
  test1:
    name: test1
    runs-on: macos-14-large
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
