name: "test1"

on:
  push:
    branches:
      - main

jobs:
  test1:
    name: test1
    runs-on: macos-14
    environment: Test
    steps:
    - uses: actions/checkout@v4
    - run: system_profiler SPDisplaysDataType
