name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        git clone https://github.com/microsoft/playwright
        cd playwright
        npm i && npm run build
        DEBUG=pw:install npx playwright install --with-deps chromium
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        DEBUG=pw:browser,pw:api npm run etest
