name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - run: |
        git clone https://github.com/microsoft/playwright
        cd playwright
        npm i && npm run build
        DEBUG=pw:install npx playwright install --with-deps chromium
        --headless --timeout=5000 --screenshot=screenshot.png https://www.costco.com
