name: Test PR WebKit Ubuntu

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # It fails here: https://github.com/git/git/blob/master/setup.c#L1290
    - run: |
          echo "Hello I'm user $(whoami) with id $(id)"
          ls -lad $GITHUB_WORKSPACE
          gcc -o check_root check_root.c
          ./check_root
          git ls-files --others --exclude-standard
