name: Test PR WebKit Ubuntu

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: |
          git ls-files --others --exclude-standard
          git rev-parse --show-toplevel
          whoami
          ls -la
