name: Test PR WebKit Ubuntu

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
    - run: |
        sudo apt-get install -y firefox
        file /usr/bin/firefox
