name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        git clone https://github.com/microsoft/playwright
        cd playwright
        npm i && npm run build
        ls -la /home/runner/work/test/test/playwright/node_modules/electron/dist/chrome-sandbox
        npx playwright install --with-deps chromium
        DEBUG=pw:api,pw:browser xvfb-run npm run etest
