name: "tests repro"

on:
  push:
    branches:
      - main

jobs:
  test_upload:
    name: upload
    runs-on: macos-14-large
    steps:
    - uses: actions/checkout@v4
    - run: arch

  test_upload2:
    name: upload
    runs-on: macos-14-xlarge
    steps:
    - uses: actions/checkout@v4
    - run: arch
