name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - run: |
        git clone https://github.com/microsoft/playwright-browsers
        cd playwright
        npm i && npm run build
        df -h
        npx playwright install --with-deps
        df -h
        npm run wtest
        df -h
