name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        echo "Consider running tests from slow files in parallel, see https://playwright.dev/docs/test-parallel."
