name: "test1"

on:
  push:
    branches:
      - main

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v4
    - run: echo "echo \$FOO" >> test.sh
    - run: sudo bash test.sh
      env:
        FOO: 123
