name: "test1"

on:
  push:
    branches:
      - main

jobs:
  test1:
    name: test1
    runs-on: ${{ matrix.runs-on }}
    environment: Test
    strategy:
      matrix:
        runs-on: [macos-12, macos-13, macos-14]
    steps:
    - uses: actions/checkout@v4
    - name: Allow microphone access to all apps (macOS 14)
      shell: bash
      run: |
        if [[ "$(uname)" != "Darwin" ]]; then
          echo "Not macOS, exiting"
          exit 0
        fi
        echo "Allowing microphone access to all apps"
        version=$(sw_vers -productVersion | cut -d. -f1)
        if [[ "$version" == "14" ]]; then
          sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR IGNORE INTO access VALUES ('kTCCServiceMicrophone','/usr/local/opt/runner/provisioner/provisioner',1,2,4,1,NULL,NULL,0,'UNUSED',NULL,0,1687786159,NULL,NULL,'UNUSED',1687786159);"
        elif [[ "$version" == "12" || "$version" == "13" ]]; then
          sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceMicrophone','/usr/local/opt/runner/provisioner/provisioner',1,2,4,1,NULL,NULL,0,'UNUSED',NULL,0,1687786159);"
        else
          echo "macOS version is unsupported. Version is $version, exiting"
          exit 1
        fi
        echo "Successfully allowed microphone access"