name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - run: |
        curl -fsSL get.docker.com | sh
        
        sudo service docker stop
        sudo mv /var/lib/docker /mnt/docker
        echo '{ "data-root": "/mnt/docker" }' | sudo tee /etc/docker/daemon.json
        sudo service docker start
        
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        
